import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | 8K IoT Solutions',
  description: 'Terms and conditions governing the professional services and website use of 8K IoT Solutions.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-zinc-900 font-sans selection:bg-zinc-100 antialiased">
      <div className="max-w-3xl mx-auto px-8 pt-24 pb-32">
        {/* Simple Navigation */}
        <nav className="mb-16">
          <Link 
            href="/" 
            className="text-sm font-medium text-zinc-400 hover:text-zinc-900 transition-colors uppercase tracking-widest"
          >
            ← Back to Home
          </Link>
        </nav>

        {/* Document Header */}
        <header className="mb-16 border-b border-zinc-100 pb-12">
          <h1 className="text-3xl font-bold tracking-tight mb-4 text-zinc-900">
            Terms of Service
          </h1>
          <div className="flex flex-col gap-1 text-sm text-zinc-500 font-medium">
            <span>Effective Date: April 7, 2026</span>
            <span>Last Updated: April 7, 2026</span>
          </div>
        </header>

        {/* Document Content */}
        <div className="space-y-12 text-zinc-600 leading-relaxed text-[15px]">
          <section>
            <p className="mb-6">
              These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement between you and 8K IoT Solutions (&quot;the Studio&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) regarding your use of our website and the procurement of our professional hardware and software services.
            </p>
            <p>
              By utilizing our services, you agree to be bound by these Terms. If you do not agree, you must cease all use of our services immediately.
            </p>
          </section>

          <section>
            <h2 className="text-zinc-900 font-bold uppercase tracking-wider text-xs mb-6 underline decoration-zinc-100 underline-offset-8">1.0 Professional Services</h2>
            <div className="space-y-4">
              <p>
                8K IoT Solutions provides specialized engineering and development services including, but not limited to:
              </p>
              <ul className="list-none space-y-3 pl-0 border-l border-zinc-100 pl-6 ml-1">
                <li><span className="font-bold text-zinc-800">1.1 Hardware Prototyping:</span> Circuit design, PCB layout, and component sourcing.</li>
                <li><span className="font-bold text-zinc-800">1.2 Software Development:</span> Firmware, web dashboards, and mobile application interfaces.</li>
                <li><span className="font-bold text-zinc-800">1.3 IoT Integration:</span> End-to-end connectivity solutions and data management.</li>
              </ul>
              <p className="text-sm italic">
                Specific project deliverables and timelines are governed by separate Service Level Agreements (SLAs) or project-specific contracts.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-zinc-900 font-bold uppercase tracking-wider text-xs mb-6 underline decoration-zinc-100 underline-offset-8">2.0 Intellectual Property</h2>
            <p className="mb-4">
              Unless otherwise specified in a written contract:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>All preliminary designs, source code, and CAD files generated by the Studio remain the intellectual property of 8K IoT Solutions until full payment is rendered.</li>
              <li>Trademarks, logos, and website content are protected by copyright and may not be reproduced without express written consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-zinc-900 font-bold uppercase tracking-wider text-xs mb-6 underline decoration-zinc-100 underline-offset-8">3.0 Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, 8K IoT Solutions shall not be held liable for any indirect, incidental, or consequential damages resulting from hardware failures, software bugs, or data loss encountered during or after the implementation of a project. Our total liability for any claim shall not exceed the amount paid for the specific service in question.
            </p>
          </section>

          <section>
            <h2 className="text-zinc-900 font-bold uppercase tracking-wider text-xs mb-6 underline decoration-zinc-100 underline-offset-8">4.0 Termination of Service</h2>
            <p>
              We reserve the right to suspend or terminate services at our discretion if these Terms are breached, or if project requirements evolve beyond the initial agreed scope without mutual adjustment of terms.
            </p>
          </section>

          <section>
            <h2 className="text-zinc-900 font-bold uppercase tracking-wider text-xs mb-6 underline decoration-zinc-100 underline-offset-8">5.0 Governing Law & Submission to Jurisdiction</h2>
            <p>
              These Terms shall be interpreted and enforced under the laws of the Republic of the Philippines. By using our services, you irrevocably submit to the exclusive jurisdiction of the regional trial courts of Talisay City, Negros Occidental for the resolution of any legal proceedings.
            </p>
          </section>

          <section className="pt-12 border-t border-zinc-100">
            <h2 className="text-zinc-900 font-bold uppercase tracking-wider text-xs mb-4">Contractual Inquiries</h2>
            <p className="text-sm">
              For questions regarding these terms or to request a formal service agreement, please contact:<br />
              <span className="font-bold text-zinc-900">8K IoT Solutions Administration</span><br />
              Email: iotsolutions0@gmail.com<br />
              Location: Talisay City, Negros Occidental, PH
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
