create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 120),
  logo_url text not null check (char_length(logo_url) between 1 and 2048),
  website_url text check (website_url is null or char_length(website_url) <= 2048),
  display_index integer not null default 0 check (display_index >= 0),
  is_visible boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists clients_visible_display_index_idx
on public.clients (display_index, id)
where is_visible = true;

create or replace function public.set_current_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_clients_updated_at on public.clients;
create trigger set_clients_updated_at
before update on public.clients
for each row
execute function public.set_current_updated_at();

alter table public.clients enable row level security;

revoke all on public.clients from anon, authenticated;
revoke all on sequence public.clients_id_seq from anon, authenticated;
grant select, insert, update, delete on public.clients to service_role;
grant usage, select on sequence public.clients_id_seq to service_role;

insert into public.clients (name, logo_url, display_index)
values
  ('Adriano''s Coffee', '/clients/adrianos-coffee.svg', 0),
  ('RoastBloxx', '/clients/roastbloxx.svg', 1),
  ('Technowatch', '/clients/technowatch.svg', 2),
  ('Sherack Dojillo', '/clients/sherack-dojillo.svg', 3)
on conflict (name) do nothing;

notify pgrst, 'reload schema';
