create table if not exists public.tech_stack (
  id integer generated by default as identity primary key,
  name text not null,
  logo_url text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.tech_stack add column if not exists name text;
alter table public.tech_stack add column if not exists logo_url text;
alter table public.tech_stack add column if not exists created_at timestamptz not null default timezone('utc', now());
alter table public.tech_stack add column if not exists updated_at timestamptz not null default timezone('utc', now());

create or replace function public.set_current_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_tech_stack_updated_at on public.tech_stack;
create trigger set_tech_stack_updated_at
before update on public.tech_stack
for each row
execute function public.set_current_updated_at();

alter table public.tech_stack enable row level security;

revoke all on public.tech_stack from anon, authenticated;

grant select, insert, update, delete on public.tech_stack to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
