create table if not exists public.projects (
  id integer generated by default as identity primary key,
  title text not null,
  category text not null,
  role text,
  year text,
  description text,
  image_url text,
  gallery_urls text[] not null default '{}',
  is_featured boolean not null default false,
  project_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.projects add column if not exists role text;
alter table public.projects add column if not exists year text;
alter table public.projects add column if not exists description text;
alter table public.projects add column if not exists image_url text;
alter table public.projects add column if not exists gallery_urls text[] not null default '{}';
alter table public.projects add column if not exists is_featured boolean not null default false;
alter table public.projects add column if not exists project_url text;
alter table public.projects add column if not exists created_at timestamptz not null default timezone('utc', now());
alter table public.projects add column if not exists updated_at timestamptz not null default timezone('utc', now());

create table if not exists public.inquiries (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  email text not null,
  message text not null
);

create or replace function public.set_current_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row
execute function public.set_current_updated_at();

alter table public.projects enable row level security;
alter table public.inquiries enable row level security;

revoke all on public.projects from anon, authenticated;
revoke all on public.inquiries from anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.projects to service_role;
grant select, insert, update, delete on public.inquiries to service_role;
grant usage, select on all sequences in schema public to service_role;
